### ISSUE TITLE
HTTP ToolKit doesn't work after patcher

### ISSUE THREAD

**Issue by scorpioRED** [XielQs/httptoolkit-pro-patcher#23]
<img width="1309" alt="Screenshot 2024-11-04 at 18 50 11" src="https://github.com/user-attachments/assets/bd06c59a-7ed9-40e9-842e-a059657e9f50">

**Comment by scorpioRED** [comment]
Mac OS Sequoia 15.1

**Comment by scorpioRED** [comment]
<img width="1594" alt="Screenshot 2024-11-04 at 18 55 17" src="https://github.com/user-attachments/assets/6548112f-204e-4ccd-814e-5029abbb8551">
<img width="1316" alt="Screenshot 2024-11-04 at 18 56 34" src="https://github.com/user-attachments/assets/2194946e-e1b1-47be-a5c1-593b4ac45539">

**Comment by XielQs** [comment]
can you share debug logs using `node . start`

**Comment by scorpioRED** [comment]
<img width="1058" alt="Screenshot 2024-11-04 at 19 05 13" src="https://github.com/user-attachments/assets/a1fe14a0-5b23-452a-8a35-6c70b87ba0f3">

Nothing there

**Comment by scorpioRED** [comment]
<img width="846" alt="Screenshot 2024-11-04 at 19 06 18" src="https://github.com/user-attachments/assets/0433cd58-1769-4f57-946d-58c104d501e0">
Nothing there

**Comment by scorpioRED** [comment]
<img width="1504" alt="Screenshot 2024-11-04 at 19 08 10" src="https://github.com/user-attachments/assets/18c25295-e1fc-4f50-add4-7b9c0bfe5cca">

**Comment by scorpioRED** [comment]
<img width="1507" alt="Screenshot 2024-11-04 at 19 09 11" src="https://github.com/user-attachments/assets/0dc038c6-d301-4690-82d3-f7e242703302">

**Comment by XielQs** [comment]
uh maybe try repatching again? `node . restore && node . patch`

**Comment by yawnbo** [comment]
Same thing on linux after updating to 1.17.2-1
![image](https://github.com/user-attachments/assets/27b90212-43ab-4ff6-8415-0d5763fa3fa5)

**Comment by bocubon** [comment]
Same errors and here are the log:

--- Launching HTTP Toolkit desktop v1.19.0 ---
Config checked in 27 ms
Certificates setup in 11 ms
Standalone server started in 10 ms
Server started in 40 ms
Total startup took 88 ms
Running /Library/Internet Plug-Ins/JavaAppletPlugin.plugin/Contents/Home/bin/java:
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:690)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:672)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:359)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 more

=> Java attach APIs are not available

**Comment by imvast** [comment]
bump

Running java:
Exception in thread "main" java.lang.NoClassDefFoundError: com/sun/tools/attach/AgentLoadException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.sun.tools.attach.AgentLoadException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

=> Java attach APIs are not available

**Comment by Displema** [comment]
I cannot see the response for some requests (it just spins indefinitely). Mock editing isn't working and I still have the initialization dialog when starting. It looks like I'm getting ratelimited but I also got 428 status codes. Maybe did they add authentication or TLS fingerprinting?
[logs.txt](https://github.com/user-attachments/files/17638152/logs.txt)

**Comment by momoko2806** [comment]
![Untitled](https://github.com/user-attachments/assets/045fd5e1-7e10-4c49-839d-a85b0a457923)
Me too

**Comment by kane1619** [comment]
No internet connection and file is not cached

**Comment by kane1619** [comment]
PLIIIIIIISSSSSSS HEEEEEEEELP 🙏🙏🙏🙏🙏

**Comment by kewldan** [comment]
I could help and see what requests the program can't get a response to, but that would require HTTPToolkit 😂

**Comment by momoko2806** [comment]
Someone reported this github link in HTTP Toolkit
